# Use postgres/example user/password credentials

volumes:
  database-data:

networks:
  network_public:
    name: network_public
    external: true

services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
      network: network_public
    restart: always
    networks:
      - network_public
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}


# END SECTION: Optional use of Prisma Studio.